# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1131, 692)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(240, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(240, 270, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1131, 121))
        self.tabWidget.setIconSize(QtCore.QSize(36, 36))
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_2 = QtWidgets.QWidget()
        self.Tab_2.setObjectName("Tab_2")
        self.pushButton = QtWidgets.QPushButton(self.Tab_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color:\"#FF5500\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.Tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius: 10px;\n"
"background-color:\"#FF5500\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.Tab_2, "")
        self.Tab_21 = QtWidgets.QWidget()
        self.Tab_21.setObjectName("Tab_21")
        self.pushButton_2 = QtWidgets.QPushButton(self.Tab_21)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 50, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color:\"#FF5500\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.Tab_21, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_2.setText(_translate("Dialog", "Phone"))
        self.label_3.setText(_translate("Dialog", "address"))
        self.label_4.setText(_translate("Dialog", "INN"))
        self.pushButton.setText(_translate("Dialog", "Make transfer"))
        self.pushButton_3.setText(_translate("Dialog", "Issue credit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_2), _translate("Dialog", "Operations"))
        self.pushButton_2.setText(_translate("Dialog", "Create Client"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_21), _translate("Dialog", "User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
